/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IFixedPricePrimary,
  IFixedPricePrimaryInterface,
} from "../IFixedPricePrimary";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "fixedItemId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
    ],
    name: "BoughtFixedPrice",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "fixedItemId",
        type: "uint256",
      },
    ],
    name: "ListedFixedPrice",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "fixedItemId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "UnlistedFixedPrice",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "itemId",
        type: "uint256",
      },
    ],
    name: "buyItemFixedPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint96",
        name: "price",
        type: "uint96",
      },
      {
        internalType: "uint128",
        name: "tokenId",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "amount",
        type: "uint128",
      },
      {
        internalType: "uint16",
        name: "feeNumerator",
        type: "uint16",
      },
      {
        internalType: "enum IAssetCommon.AssetType",
        name: "assetType",
        type: "uint8",
      },
      {
        internalType: "string",
        name: "uri",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "listItemFixedPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "itemId",
        type: "uint256",
      },
    ],
    name: "unlistItemFixedPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFixedPricePrimary__factory {
  static readonly abi = _abi;
  static createInterface(): IFixedPricePrimaryInterface {
    return new utils.Interface(_abi) as IFixedPricePrimaryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFixedPricePrimary {
    return new Contract(address, _abi, signerOrProvider) as IFixedPricePrimary;
  }
}
