/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IAuctionSecondaryInterface extends ethers.utils.Interface {
  functions: {
    "cancelAuction(uint256)": FunctionFragment;
    "finishAuction(uint256,uint256,address,bytes)": FunctionFragment;
    "listAuction(address,uint96,uint128,uint128,uint8,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "cancelAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finishAuction",
    values: [BigNumberish, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listAuction",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finishAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listAuction",
    data: BytesLike
  ): Result;

  events: {
    "CanceledAuction(uint256,uint256)": EventFragment;
    "FinishedAuction(uint256,uint256,uint256,address)": EventFragment;
    "ListedAuction(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CanceledAuction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FinishedAuction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ListedAuction"): EventFragment;
}

export type CanceledAuctionEvent = TypedEvent<
  [BigNumber, BigNumber] & { auctionItemId: BigNumber; tokenId: BigNumber }
>;

export type FinishedAuctionEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, string] & {
    auctionItemId: BigNumber;
    tokenId: BigNumber;
    lastBid: BigNumber;
    userFinished: string;
  }
>;

export type ListedAuctionEvent = TypedEvent<
  [string, BigNumber] & { account: string; auctionItemId: BigNumber }
>;

export class IAuctionSecondary extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IAuctionSecondaryInterface;

  functions: {
    cancelAuction(
      itemId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    finishAuction(
      itemId: BigNumberish,
      bid: BigNumberish,
      buyer: string,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    listAuction(
      asset: string,
      startPrice: BigNumberish,
      tokenId: BigNumberish,
      amount: BigNumberish,
      assetType: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  cancelAuction(
    itemId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  finishAuction(
    itemId: BigNumberish,
    bid: BigNumberish,
    buyer: string,
    signature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  listAuction(
    asset: string,
    startPrice: BigNumberish,
    tokenId: BigNumberish,
    amount: BigNumberish,
    assetType: BigNumberish,
    signature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    cancelAuction(
      itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    finishAuction(
      itemId: BigNumberish,
      bid: BigNumberish,
      buyer: string,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    listAuction(
      asset: string,
      startPrice: BigNumberish,
      tokenId: BigNumberish,
      amount: BigNumberish,
      assetType: BigNumberish,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CanceledAuction(uint256,uint256)"(
      auctionItemId?: BigNumberish | null,
      tokenId?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { auctionItemId: BigNumber; tokenId: BigNumber }
    >;

    CanceledAuction(
      auctionItemId?: BigNumberish | null,
      tokenId?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { auctionItemId: BigNumber; tokenId: BigNumber }
    >;

    "FinishedAuction(uint256,uint256,uint256,address)"(
      auctionItemId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      lastBid?: BigNumberish | null,
      userFinished?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, string],
      {
        auctionItemId: BigNumber;
        tokenId: BigNumber;
        lastBid: BigNumber;
        userFinished: string;
      }
    >;

    FinishedAuction(
      auctionItemId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      lastBid?: BigNumberish | null,
      userFinished?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, string],
      {
        auctionItemId: BigNumber;
        tokenId: BigNumber;
        lastBid: BigNumber;
        userFinished: string;
      }
    >;

    "ListedAuction(address,uint256)"(
      account?: string | null,
      auctionItemId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { account: string; auctionItemId: BigNumber }
    >;

    ListedAuction(
      account?: string | null,
      auctionItemId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { account: string; auctionItemId: BigNumber }
    >;
  };

  estimateGas: {
    cancelAuction(
      itemId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    finishAuction(
      itemId: BigNumberish,
      bid: BigNumberish,
      buyer: string,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    listAuction(
      asset: string,
      startPrice: BigNumberish,
      tokenId: BigNumberish,
      amount: BigNumberish,
      assetType: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cancelAuction(
      itemId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    finishAuction(
      itemId: BigNumberish,
      bid: BigNumberish,
      buyer: string,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    listAuction(
      asset: string,
      startPrice: BigNumberish,
      tokenId: BigNumberish,
      amount: BigNumberish,
      assetType: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
