/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IFixedPricePrimaryInterface extends ethers.utils.Interface {
  functions: {
    "buyItemFixedPrice(uint256)": FunctionFragment;
    "listItemFixedPrice(address,uint96,uint128,uint128,uint16,uint8,string,bytes)": FunctionFragment;
    "unlistItemFixedPrice(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "buyItemFixedPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listItemFixedPrice",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "unlistItemFixedPrice",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "buyItemFixedPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listItemFixedPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlistItemFixedPrice",
    data: BytesLike
  ): Result;

  events: {
    "BoughtFixedPrice(uint256,address)": EventFragment;
    "ListedFixedPrice(address,uint256)": EventFragment;
    "UnlistedFixedPrice(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BoughtFixedPrice"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ListedFixedPrice"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnlistedFixedPrice"): EventFragment;
}

export type BoughtFixedPriceEvent = TypedEvent<
  [BigNumber, string] & { fixedItemId: BigNumber; buyer: string }
>;

export type ListedFixedPriceEvent = TypedEvent<
  [string, BigNumber] & { account: string; fixedItemId: BigNumber }
>;

export type UnlistedFixedPriceEvent = TypedEvent<
  [BigNumber, BigNumber] & { fixedItemId: BigNumber; tokenId: BigNumber }
>;

export class IFixedPricePrimary extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IFixedPricePrimaryInterface;

  functions: {
    buyItemFixedPrice(
      itemId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    listItemFixedPrice(
      asset: string,
      price: BigNumberish,
      tokenId: BigNumberish,
      amount: BigNumberish,
      feeNumerator: BigNumberish,
      assetType: BigNumberish,
      uri: string,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unlistItemFixedPrice(
      itemId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  buyItemFixedPrice(
    itemId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  listItemFixedPrice(
    asset: string,
    price: BigNumberish,
    tokenId: BigNumberish,
    amount: BigNumberish,
    feeNumerator: BigNumberish,
    assetType: BigNumberish,
    uri: string,
    signature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unlistItemFixedPrice(
    itemId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyItemFixedPrice(
      itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    listItemFixedPrice(
      asset: string,
      price: BigNumberish,
      tokenId: BigNumberish,
      amount: BigNumberish,
      feeNumerator: BigNumberish,
      assetType: BigNumberish,
      uri: string,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    unlistItemFixedPrice(
      itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BoughtFixedPrice(uint256,address)"(
      fixedItemId?: BigNumberish | null,
      buyer?: null
    ): TypedEventFilter<
      [BigNumber, string],
      { fixedItemId: BigNumber; buyer: string }
    >;

    BoughtFixedPrice(
      fixedItemId?: BigNumberish | null,
      buyer?: null
    ): TypedEventFilter<
      [BigNumber, string],
      { fixedItemId: BigNumber; buyer: string }
    >;

    "ListedFixedPrice(address,uint256)"(
      account?: string | null,
      fixedItemId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { account: string; fixedItemId: BigNumber }
    >;

    ListedFixedPrice(
      account?: string | null,
      fixedItemId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { account: string; fixedItemId: BigNumber }
    >;

    "UnlistedFixedPrice(uint256,uint256)"(
      fixedItemId?: BigNumberish | null,
      tokenId?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { fixedItemId: BigNumber; tokenId: BigNumber }
    >;

    UnlistedFixedPrice(
      fixedItemId?: BigNumberish | null,
      tokenId?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { fixedItemId: BigNumber; tokenId: BigNumber }
    >;
  };

  estimateGas: {
    buyItemFixedPrice(
      itemId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    listItemFixedPrice(
      asset: string,
      price: BigNumberish,
      tokenId: BigNumberish,
      amount: BigNumberish,
      feeNumerator: BigNumberish,
      assetType: BigNumberish,
      uri: string,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unlistItemFixedPrice(
      itemId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyItemFixedPrice(
      itemId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    listItemFixedPrice(
      asset: string,
      price: BigNumberish,
      tokenId: BigNumberish,
      amount: BigNumberish,
      feeNumerator: BigNumberish,
      assetType: BigNumberish,
      uri: string,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unlistItemFixedPrice(
      itemId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
